[platformio]
default_envs = stopwatch_pet

[env:stopwatch_pet]
platform = espressif32@6.12.0
framework = arduino
board = esp32s3box
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCODEX_PET_STOPWATCH=1
lib_deps =
    M5GFX = https://github.com/m5stack/M5GFX.git#729297d6e3d657ddc1ec5189bac2f2ea68828085
    M5Unified = https://github.com/m5stack/M5Unified.git#4fb444784c85791e0b0207701392b42be234b2e7
